//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGVDispatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGVDispatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agvmap {
            get {
                object obj = ResourceManager.GetObject("agvmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agvmap2 {
            get {
                object obj = ResourceManager.GetObject("agvmap2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Config xmlns=&quot;clr-namespace:AGVDispatcher.App;assembly=AGVDispatcher&quot;&gt;
        ///  &lt;_AllAGV_ByOrder&gt;
        ///    &lt;Item xmlns=&quot;https://extendedxmlserializer.github.io/system&quot;&gt;
        ///      &lt;Key&gt;1&lt;/Key&gt;
        ///      &lt;Value&gt;
        ///        &lt;AGVID&gt;1&lt;/AGVID&gt;
        ///        &lt;Order&gt;1&lt;/Order&gt;
        ///        &lt;InUse&gt;true&lt;/InUse&gt;
        ///      &lt;/Value&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/_AllAGV_ByOrder&gt;
        ///  &lt;_AllPLC_ByOrder&gt;
        ///    &lt;Item xmlns=&quot;https://extendedxmlserializer.github.io/system&quot;&gt;
        ///      &lt;Key&gt;1&lt;/Key&gt;
        ///      &lt;Value&gt;
        ///        &lt;PLCID&gt;1&lt;/PLC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dictionary xmlns:ns1=&quot;clr-namespace:AGVDispatcher.Entity;assembly=AGVDispatcher&quot; xmlns:exs=&quot;https://extendedxmlserializer.github.io/v2&quot; exs:arguments=&quot;unsignedShort,ns1:IPoint&quot; xmlns=&quot;https://extendedxmlserializer.github.io/system&quot;&gt;
        ///  &lt;Item&gt;
        ///    &lt;Key&gt;1&lt;/Key&gt;
        ///    &lt;Value exs:type=&quot;ns1:BreakZonePoint&quot;&gt;
        ///      &lt;Order&gt;0&lt;/Order&gt;
        ///      &lt;PhysicID&gt;777&lt;/PhysicID&gt;
        ///      &lt;LogicID&gt;0&lt;/LogicID&gt;
        ///    &lt;/Value&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///    &lt;Key&gt;2&lt;/Key&gt;
        ///    &lt;Value exs:type=&quot;ns1:Brea [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PLCReal {
            get {
                object obj = ResourceManager.GetObject("PLCReal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon robot_delivery {
            get {
                object obj = ResourceManager.GetObject("robot_delivery", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap robot_delivery1 {
            get {
                object obj = ResourceManager.GetObject("robot_delivery1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sample_AGV {
            get {
                object obj = ResourceManager.GetObject("sample_AGV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
